# Generated by Django 4.0.3 on 2023-05-26 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], default='buy', max_length=4)),
                ('status', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=6)),
                ('openDatetime', models.DateTimeField(blank=True, default=None)),
                ('closedDatetime', models.DateTimeField(blank=True, default=None)),
                ('PartiallyClosedDatetime', models.DateTimeField(blank=True, default=None)),
                ('amount', models.FloatField(default=0)),
                ('pricePerBitcoin', models.FloatField(default=0)),
                ('totalPrice', models.FloatField(default=0)),
                ('profitLoss', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('euroBalance', models.FloatField(default=20000)),
                ('bitcoinBalance', models.FloatField(default=0)),
                ('profitLoss', models.FloatField(default=0)),
                ('pendingBitcoin', models.FloatField(default=0)),
                ('pendingEuro', models.FloatField(default=0)),
                ('ipAddresses', models.Field(default=[])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
